### PR TITLE
Some games use plain "mono.dll"

### PR DESCRIPTION
**Pull request by Techial**
As the title states, some games use plain "mono.dll" instead of "mono-2.0-bdwgc.dll", therefore having the choice to select targeted mono module would be a nice addition.

### CODE REVIEW

**Comment by Razchek** [comment]
Good call.

Before committing to this, I need to ensure that the structural information is supported. And rather than providing the user the option, there _should_ only be those two. So simply looking for the other if one doesn't exist would provide a better user experience due to the reduced complexity (this will also make it easier to transition into IL2CPP support when the project reaches that milestone).

**Unity v20xx.x.x** (mono.dll) 
**Unity v20xx.x.x-mbe** bleeding-edge (mono-2.0-bdwgc.dll)

Did you have a game title that is currently using the standard mono library? I'd like to check the structure info before continuing.

Thank you for the PR. ❤️

**Comment by Techial** [comment]
Robocraft, Software Inc, Keep talking and nobody explodes, Holdfast Nations At War, Heliborne, Gang Beasts Online (At least in beta), Death Toll and Battlerite are the ones I remember from the top of my head

**Comment by Techial** [comment]
Totally Accurate Battlegrounds

**Comment by Razchek** [comment]
Thank you. I went and took a look at the games that were available freely from that list.
Robocraft is 32-bit. 32-bit is unsupported. I took a look regardless, and the structures were expectantly different.
Battlerite is 32-bit and uses Unity 5.4. I decided to skip this because of that.
Death Toll is using Unity 2017.4.1. This was a promising result, but unfortunately the structure information was different.

Instead of continuing to shotgun for a match I went and took a look at the source code for both the standard mono and bleeding edge versions (I should have done this in the first place). And unfortunately 'standard mono' expectantly has differences from the bleeding edge revision. While supporting the standard mono module is possible with some more R&D; the current model of the project cannot dissect information from the standard mono module without multiple changes.

Here is `_MonoClass` from each mono version for comparison:

- https://github.com/Unity-Technologies/mono/blob/unity-2018.4/mono/metadata/class-internals.h#L290
- https://github.com/Unity-Technologies/mono/blob/unity-2018.4-mbe/mono/metadata/class-internals.h#L267

As such I won't commit these changes, but instead open an issue to later reflect on this to decide on how to add support when dynamic structures are implemented in Unispect.

**Pull request closed without merging**
